include ../make_env.mk

# Vivado variables (user-defined)
export VIVADO_PROJ_NAME := distortion
export VIVADO_VENDOR := niiichtsy
export VIVADO_LIBRARY := muleon

# IP library paths
# IP_LIBRARY_PATH := ip/

# Library dependecies
# LIB_DEPS +=
