TOPLEVEL_LANG ?= verilog

VERILOG_SOURCES = ../src/adau1761_spi_configurator.v
TOPLEVEL := adau1761_spi_configurator
MODULE   := adau1761_spi_configurator_test

include $(shell cocotb-config --makefiles)/Makefile.sim
